# Generated by Django 3.0 on 2019-12-14 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug :')),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='Profile_imge', verbose_name='Image :')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country :')),
                ('address', models.CharField(max_length=50, verbose_name='Address :')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joindate', models.DateTimeField(auto_now=True, verbose_name='Join Date :')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User :')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
